# Generated by Django 5.1.15 on 2026-09-01 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('HEALTH', 'Health'), ('FITNESS', 'Fitness'), ('CAREER', 'Career'), ('LEARNING', 'Learning'), ('CODING', 'Coding'), ('RESEARCH', 'Research'), ('PERSONAL', 'Personal'), ('OTHER', 'Other')], db_index=True, default='PERSONAL', max_length=50)),
                ('target_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('unit', models.CharField(default='boolean', max_length=50)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], db_index=True, default='DAILY', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='arcs.arc')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'db_table': 'goals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['arc', 'is_active'], name='goals_arc_id_c25389_idx')],
            },
        ),
    ]
