# Generated by Django 5.1.15 on 2026-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcs', '0001_initial'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AddField(
            model_name='goal',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['arc', 'order'], name='goals_arc_id_a59117_idx'),
        ),
    ]
