# Generated by Django 5.1.15 on 2026-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_options_goal_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='active_days',
            field=models.CharField(default='MON,TUE,WED,THU,FRI,SAT,SUN', help_text='Comma-separated days of week when this goal is active, e.g. MON,TUE,WED,THU,FRI', max_length=100),
        ),
    ]
