# Generated by Django 5.1.15 on 2026-09-01 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('day_number', models.PositiveSmallIntegerField(blank=True, help_text='Day 1-7 in split', null=True)),
                ('date', models.DateField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
                'db_table': 'workouts',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=255)),
                ('primary_focus', models.CharField(blank=True, default='', max_length=255)),
                ('target_sets', models.PositiveIntegerField(default=3)),
                ('target_reps', models.CharField(blank=True, default='8-12', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'Workout Exercise',
                'verbose_name_plural': 'Workout Exercises',
                'db_table': 'workout_exercises',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_number', models.PositiveIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutexercise')),
            ],
            options={
                'verbose_name': 'Workout Set',
                'verbose_name_plural': 'Workout Sets',
                'db_table': 'workout_sets',
                'ordering': ['set_number'],
            },
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'date'], name='workouts_user_id_9fde5e_idx'),
        ),
    ]
