# Generated by Django 5.1.15 on 2026-09-01 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='goals.goal')),
            ],
            options={
                'verbose_name': 'Daily Log',
                'verbose_name_plural': 'Daily Logs',
                'db_table': 'daily_logs',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['goal', 'date'], name='daily_logs_goal_id_054c6e_idx'), models.Index(fields=['date', 'completed'], name='daily_logs_date_a256af_idx')],
                'constraints': [models.UniqueConstraint(fields=('goal', 'date'), name='unique_goal_date')],
            },
        ),
    ]
